/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileeditRouteImport } from './routes/profileedit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MapRouteImport } from './routes/map'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DataTableDemoRouteImport } from './routes/data-table-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganisationsDashboardRouteImport } from './routes/organisations/dashboard'
import { Route as CspCspIdRouteImport } from './routes/csp/$cspId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRequestRouteImport } from './routes/auth/request'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAdminOnlyRouteImport } from './routes/auth/adminOnly'
import { Route as ApplicantsApplicantIdRouteImport } from './routes/applicants/$applicantId'
import { Route as AdminDashboard2RouteImport } from './routes/admin/dashboard2'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCspIdRouteImport } from './routes/admin/cspId'
import { Route as OrganisationsProjectsNewRouteImport } from './routes/organisations/projects/new'
import { Route as OrganisationsListingapplicationsProjectIdRouteImport } from './routes/organisations/listingapplications/$projectId'
import { Route as CspCspIdApplyRouteImport } from './routes/csp/$cspId/apply'

const ProfileeditRoute = ProfileeditRouteImport.update({
  id: '/profileedit',
  path: '/profileedit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableDemoRoute = DataTableDemoRouteImport.update({
  id: '/data-table-demo',
  path: '/data-table-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsDashboardRoute = OrganisationsDashboardRouteImport.update({
  id: '/organisations/dashboard',
  path: '/organisations/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CspCspIdRoute = CspCspIdRouteImport.update({
  id: '/csp/$cspId',
  path: '/csp/$cspId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestRoute = AuthRequestRouteImport.update({
  id: '/auth/request',
  path: '/auth/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminOnlyRoute = AuthAdminOnlyRouteImport.update({
  id: '/auth/adminOnly',
  path: '/auth/adminOnly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantsApplicantIdRoute = ApplicantsApplicantIdRouteImport.update({
  id: '/applicants/$applicantId',
  path: '/applicants/$applicantId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboard2Route = AdminDashboard2RouteImport.update({
  id: '/admin/dashboard2',
  path: '/admin/dashboard2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCspIdRoute = AdminCspIdRouteImport.update({
  id: '/admin/cspId',
  path: '/admin/cspId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsProjectsNewRoute =
  OrganisationsProjectsNewRouteImport.update({
    id: '/organisations/projects/new',
    path: '/organisations/projects/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganisationsListingapplicationsProjectIdRoute =
  OrganisationsListingapplicationsProjectIdRouteImport.update({
    id: '/organisations/listingapplications/$projectId',
    path: '/organisations/listingapplications/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CspCspIdApplyRoute = CspCspIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CspCspIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data-table-demo': typeof DataTableDemoRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/map': typeof MapRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/profileedit': typeof ProfileeditRoute
  '/admin/cspId': typeof AdminCspIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboard2': typeof AdminDashboard2Route
  '/applicants/$applicantId': typeof ApplicantsApplicantIdRoute
  '/auth/adminOnly': typeof AuthAdminOnlyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request': typeof AuthRequestRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/csp/$cspId': typeof CspCspIdRouteWithChildren
  '/organisations/dashboard': typeof OrganisationsDashboardRoute
  '/csp/$cspId/apply': typeof CspCspIdApplyRoute
  '/organisations/listingapplications/$projectId': typeof OrganisationsListingapplicationsProjectIdRoute
  '/organisations/projects/new': typeof OrganisationsProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data-table-demo': typeof DataTableDemoRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/map': typeof MapRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/profileedit': typeof ProfileeditRoute
  '/admin/cspId': typeof AdminCspIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboard2': typeof AdminDashboard2Route
  '/applicants/$applicantId': typeof ApplicantsApplicantIdRoute
  '/auth/adminOnly': typeof AuthAdminOnlyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request': typeof AuthRequestRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/csp/$cspId': typeof CspCspIdRouteWithChildren
  '/organisations/dashboard': typeof OrganisationsDashboardRoute
  '/csp/$cspId/apply': typeof CspCspIdApplyRoute
  '/organisations/listingapplications/$projectId': typeof OrganisationsListingapplicationsProjectIdRoute
  '/organisations/projects/new': typeof OrganisationsProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data-table-demo': typeof DataTableDemoRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/map': typeof MapRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/profileedit': typeof ProfileeditRoute
  '/admin/cspId': typeof AdminCspIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboard2': typeof AdminDashboard2Route
  '/applicants/$applicantId': typeof ApplicantsApplicantIdRoute
  '/auth/adminOnly': typeof AuthAdminOnlyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request': typeof AuthRequestRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/csp/$cspId': typeof CspCspIdRouteWithChildren
  '/organisations/dashboard': typeof OrganisationsDashboardRoute
  '/csp/$cspId/apply': typeof CspCspIdApplyRoute
  '/organisations/listingapplications/$projectId': typeof OrganisationsListingapplicationsProjectIdRoute
  '/organisations/projects/new': typeof OrganisationsProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/data-table-demo'
    | '/discover'
    | '/favourites'
    | '/map'
    | '/my-applications'
    | '/profile'
    | '/profileedit'
    | '/admin/cspId'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/applicants/$applicantId'
    | '/auth/adminOnly'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/request'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/csp/$cspId'
    | '/organisations/dashboard'
    | '/csp/$cspId/apply'
    | '/organisations/listingapplications/$projectId'
    | '/organisations/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/data-table-demo'
    | '/discover'
    | '/favourites'
    | '/map'
    | '/my-applications'
    | '/profile'
    | '/profileedit'
    | '/admin/cspId'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/applicants/$applicantId'
    | '/auth/adminOnly'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/request'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/csp/$cspId'
    | '/organisations/dashboard'
    | '/csp/$cspId/apply'
    | '/organisations/listingapplications/$projectId'
    | '/organisations/projects/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/data-table-demo'
    | '/discover'
    | '/favourites'
    | '/map'
    | '/my-applications'
    | '/profile'
    | '/profileedit'
    | '/admin/cspId'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/applicants/$applicantId'
    | '/auth/adminOnly'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/request'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/csp/$cspId'
    | '/organisations/dashboard'
    | '/csp/$cspId/apply'
    | '/organisations/listingapplications/$projectId'
    | '/organisations/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DataTableDemoRoute: typeof DataTableDemoRoute
  DiscoverRoute: typeof DiscoverRoute
  FavouritesRoute: typeof FavouritesRoute
  MapRoute: typeof MapRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  ProfileRoute: typeof ProfileRoute
  ProfileeditRoute: typeof ProfileeditRoute
  AdminCspIdRoute: typeof AdminCspIdRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDashboard2Route: typeof AdminDashboard2Route
  ApplicantsApplicantIdRoute: typeof ApplicantsApplicantIdRoute
  AuthAdminOnlyRoute: typeof AuthAdminOnlyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRequestRoute: typeof AuthRequestRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CspCspIdRoute: typeof CspCspIdRouteWithChildren
  OrganisationsDashboardRoute: typeof OrganisationsDashboardRoute
  OrganisationsListingapplicationsProjectIdRoute: typeof OrganisationsListingapplicationsProjectIdRoute
  OrganisationsProjectsNewRoute: typeof OrganisationsProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profileedit': {
      id: '/profileedit'
      path: '/profileedit'
      fullPath: '/profileedit'
      preLoaderRoute: typeof ProfileeditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-table-demo': {
      id: '/data-table-demo'
      path: '/data-table-demo'
      fullPath: '/data-table-demo'
      preLoaderRoute: typeof DataTableDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/dashboard': {
      id: '/organisations/dashboard'
      path: '/organisations/dashboard'
      fullPath: '/organisations/dashboard'
      preLoaderRoute: typeof OrganisationsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/$cspId': {
      id: '/csp/$cspId'
      path: '/csp/$cspId'
      fullPath: '/csp/$cspId'
      preLoaderRoute: typeof CspCspIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/request': {
      id: '/auth/request'
      path: '/auth/request'
      fullPath: '/auth/request'
      preLoaderRoute: typeof AuthRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/adminOnly': {
      id: '/auth/adminOnly'
      path: '/auth/adminOnly'
      fullPath: '/auth/adminOnly'
      preLoaderRoute: typeof AuthAdminOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicants/$applicantId': {
      id: '/applicants/$applicantId'
      path: '/applicants/$applicantId'
      fullPath: '/applicants/$applicantId'
      preLoaderRoute: typeof ApplicantsApplicantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard2': {
      id: '/admin/dashboard2'
      path: '/admin/dashboard2'
      fullPath: '/admin/dashboard2'
      preLoaderRoute: typeof AdminDashboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cspId': {
      id: '/admin/cspId'
      path: '/admin/cspId'
      fullPath: '/admin/cspId'
      preLoaderRoute: typeof AdminCspIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/projects/new': {
      id: '/organisations/projects/new'
      path: '/organisations/projects/new'
      fullPath: '/organisations/projects/new'
      preLoaderRoute: typeof OrganisationsProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/listingapplications/$projectId': {
      id: '/organisations/listingapplications/$projectId'
      path: '/organisations/listingapplications/$projectId'
      fullPath: '/organisations/listingapplications/$projectId'
      preLoaderRoute: typeof OrganisationsListingapplicationsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/$cspId/apply': {
      id: '/csp/$cspId/apply'
      path: '/apply'
      fullPath: '/csp/$cspId/apply'
      preLoaderRoute: typeof CspCspIdApplyRouteImport
      parentRoute: typeof CspCspIdRoute
    }
  }
}

interface CspCspIdRouteChildren {
  CspCspIdApplyRoute: typeof CspCspIdApplyRoute
}

const CspCspIdRouteChildren: CspCspIdRouteChildren = {
  CspCspIdApplyRoute: CspCspIdApplyRoute,
}

const CspCspIdRouteWithChildren = CspCspIdRoute._addFileChildren(
  CspCspIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DataTableDemoRoute: DataTableDemoRoute,
  DiscoverRoute: DiscoverRoute,
  FavouritesRoute: FavouritesRoute,
  MapRoute: MapRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  ProfileRoute: ProfileRoute,
  ProfileeditRoute: ProfileeditRoute,
  AdminCspIdRoute: AdminCspIdRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDashboard2Route: AdminDashboard2Route,
  ApplicantsApplicantIdRoute: ApplicantsApplicantIdRoute,
  AuthAdminOnlyRoute: AuthAdminOnlyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRequestRoute: AuthRequestRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CspCspIdRoute: CspCspIdRouteWithChildren,
  OrganisationsDashboardRoute: OrganisationsDashboardRoute,
  OrganisationsListingapplicationsProjectIdRoute:
    OrganisationsListingapplicationsProjectIdRoute,
  OrganisationsProjectsNewRoute: OrganisationsProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
