/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileeditRouteImport } from './routes/profileedit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MapRouteImport } from './routes/map'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DataTableDemoRouteImport } from './routes/data-table-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganisationsProfileRouteImport } from './routes/organisations/profile'
import { Route as OrganisationsNewRouteImport } from './routes/organisations/new'
import { Route as OrganisationsEditprofileRouteImport } from './routes/organisations/editprofile'
import { Route as OrganisationsDashboardRouteImport } from './routes/organisations/dashboard'
import { Route as OrganisationsProjectIdRouteImport } from './routes/organisations/$projectId'
import { Route as CspProjectIDRouteImport } from './routes/csp/$projectID'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRequestRouteImport } from './routes/auth/request'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAdminOnlyRouteImport } from './routes/auth/adminOnly'
import { Route as AdminOrganisationsRouteImport } from './routes/admin/organisations'
import { Route as AdminDashboard2RouteImport } from './routes/admin/dashboard2'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCspIdRouteImport } from './routes/admin/cspId'
import { Route as OrganisationsPreviewProjectPreviewRouteImport } from './routes/organisations/preview/$projectPreview'
import { Route as OrganisationsListingNewRouteImport } from './routes/organisations/listing/new'
import { Route as CspCspIdApplyRouteImport } from './routes/csp/$cspId/apply'
import { Route as OrganisationsApplicantProjectIdApplicantIdRouteImport } from './routes/organisations/applicant/$projectId/$applicantId'

const ProfileeditRoute = ProfileeditRouteImport.update({
  id: '/profileedit',
  path: '/profileedit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableDemoRoute = DataTableDemoRouteImport.update({
  id: '/data-table-demo',
  path: '/data-table-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsProfileRoute = OrganisationsProfileRouteImport.update({
  id: '/organisations/profile',
  path: '/organisations/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsNewRoute = OrganisationsNewRouteImport.update({
  id: '/organisations/new',
  path: '/organisations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsEditprofileRoute =
  OrganisationsEditprofileRouteImport.update({
    id: '/organisations/editprofile',
    path: '/organisations/editprofile',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganisationsDashboardRoute = OrganisationsDashboardRouteImport.update({
  id: '/organisations/dashboard',
  path: '/organisations/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsProjectIdRoute = OrganisationsProjectIdRouteImport.update({
  id: '/organisations/$projectId',
  path: '/organisations/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const CspProjectIDRoute = CspProjectIDRouteImport.update({
  id: '/csp/$projectID',
  path: '/csp/$projectID',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestRoute = AuthRequestRouteImport.update({
  id: '/auth/request',
  path: '/auth/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminOnlyRoute = AuthAdminOnlyRouteImport.update({
  id: '/auth/adminOnly',
  path: '/auth/adminOnly',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganisationsRoute = AdminOrganisationsRouteImport.update({
  id: '/admin/organisations',
  path: '/admin/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboard2Route = AdminDashboard2RouteImport.update({
  id: '/admin/dashboard2',
  path: '/admin/dashboard2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCspIdRoute = AdminCspIdRouteImport.update({
  id: '/admin/cspId',
  path: '/admin/cspId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsPreviewProjectPreviewRoute =
  OrganisationsPreviewProjectPreviewRouteImport.update({
    id: '/organisations/preview/$projectPreview',
    path: '/organisations/preview/$projectPreview',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganisationsListingNewRoute = OrganisationsListingNewRouteImport.update({
  id: '/organisations/listing/new',
  path: '/organisations/listing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CspCspIdApplyRoute = CspCspIdApplyRouteImport.update({
  id: '/csp/$cspId/apply',
  path: '/csp/$cspId/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsApplicantProjectIdApplicantIdRoute =
  OrganisationsApplicantProjectIdApplicantIdRouteImport.update({
    id: '/organisations/applicant/$projectId/$applicantId',
    path: '/organisations/applicant/$projectId/$applicantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data-table-demo': typeof DataTableDemoRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/map': typeof MapRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/profileedit': typeof ProfileeditRoute
  '/admin/cspId': typeof AdminCspIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboard2': typeof AdminDashboard2Route
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/auth/adminOnly': typeof AuthAdminOnlyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request': typeof AuthRequestRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/csp/$projectID': typeof CspProjectIDRoute
  '/organisations/$projectId': typeof OrganisationsProjectIdRoute
  '/organisations/dashboard': typeof OrganisationsDashboardRoute
  '/organisations/editprofile': typeof OrganisationsEditprofileRoute
  '/organisations/new': typeof OrganisationsNewRoute
  '/organisations/profile': typeof OrganisationsProfileRoute
  '/csp/$cspId/apply': typeof CspCspIdApplyRoute
  '/organisations/listing/new': typeof OrganisationsListingNewRoute
  '/organisations/preview/$projectPreview': typeof OrganisationsPreviewProjectPreviewRoute
  '/organisations/applicant/$projectId/$applicantId': typeof OrganisationsApplicantProjectIdApplicantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data-table-demo': typeof DataTableDemoRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/map': typeof MapRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/profileedit': typeof ProfileeditRoute
  '/admin/cspId': typeof AdminCspIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboard2': typeof AdminDashboard2Route
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/auth/adminOnly': typeof AuthAdminOnlyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request': typeof AuthRequestRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/csp/$projectID': typeof CspProjectIDRoute
  '/organisations/$projectId': typeof OrganisationsProjectIdRoute
  '/organisations/dashboard': typeof OrganisationsDashboardRoute
  '/organisations/editprofile': typeof OrganisationsEditprofileRoute
  '/organisations/new': typeof OrganisationsNewRoute
  '/organisations/profile': typeof OrganisationsProfileRoute
  '/csp/$cspId/apply': typeof CspCspIdApplyRoute
  '/organisations/listing/new': typeof OrganisationsListingNewRoute
  '/organisations/preview/$projectPreview': typeof OrganisationsPreviewProjectPreviewRoute
  '/organisations/applicant/$projectId/$applicantId': typeof OrganisationsApplicantProjectIdApplicantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/data-table-demo': typeof DataTableDemoRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/map': typeof MapRoute
  '/my-applications': typeof MyApplicationsRoute
  '/profile': typeof ProfileRoute
  '/profileedit': typeof ProfileeditRoute
  '/admin/cspId': typeof AdminCspIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dashboard2': typeof AdminDashboard2Route
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/auth/adminOnly': typeof AuthAdminOnlyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request': typeof AuthRequestRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/csp/$projectID': typeof CspProjectIDRoute
  '/organisations/$projectId': typeof OrganisationsProjectIdRoute
  '/organisations/dashboard': typeof OrganisationsDashboardRoute
  '/organisations/editprofile': typeof OrganisationsEditprofileRoute
  '/organisations/new': typeof OrganisationsNewRoute
  '/organisations/profile': typeof OrganisationsProfileRoute
  '/csp/$cspId/apply': typeof CspCspIdApplyRoute
  '/organisations/listing/new': typeof OrganisationsListingNewRoute
  '/organisations/preview/$projectPreview': typeof OrganisationsPreviewProjectPreviewRoute
  '/organisations/applicant/$projectId/$applicantId': typeof OrganisationsApplicantProjectIdApplicantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/data-table-demo'
    | '/discover'
    | '/favourites'
    | '/map'
    | '/my-applications'
    | '/profile'
    | '/profileedit'
    | '/admin/cspId'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/admin/organisations'
    | '/auth/adminOnly'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/request'
    | '/auth/reset-password'
    | '/csp/$projectID'
    | '/organisations/$projectId'
    | '/organisations/dashboard'
    | '/organisations/editprofile'
    | '/organisations/new'
    | '/organisations/profile'
    | '/csp/$cspId/apply'
    | '/organisations/listing/new'
    | '/organisations/preview/$projectPreview'
    | '/organisations/applicant/$projectId/$applicantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/data-table-demo'
    | '/discover'
    | '/favourites'
    | '/map'
    | '/my-applications'
    | '/profile'
    | '/profileedit'
    | '/admin/cspId'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/admin/organisations'
    | '/auth/adminOnly'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/request'
    | '/auth/reset-password'
    | '/csp/$projectID'
    | '/organisations/$projectId'
    | '/organisations/dashboard'
    | '/organisations/editprofile'
    | '/organisations/new'
    | '/organisations/profile'
    | '/csp/$cspId/apply'
    | '/organisations/listing/new'
    | '/organisations/preview/$projectPreview'
    | '/organisations/applicant/$projectId/$applicantId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/data-table-demo'
    | '/discover'
    | '/favourites'
    | '/map'
    | '/my-applications'
    | '/profile'
    | '/profileedit'
    | '/admin/cspId'
    | '/admin/dashboard'
    | '/admin/dashboard2'
    | '/admin/organisations'
    | '/auth/adminOnly'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/request'
    | '/auth/reset-password'
    | '/csp/$projectID'
    | '/organisations/$projectId'
    | '/organisations/dashboard'
    | '/organisations/editprofile'
    | '/organisations/new'
    | '/organisations/profile'
    | '/csp/$cspId/apply'
    | '/organisations/listing/new'
    | '/organisations/preview/$projectPreview'
    | '/organisations/applicant/$projectId/$applicantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DataTableDemoRoute: typeof DataTableDemoRoute
  DiscoverRoute: typeof DiscoverRoute
  FavouritesRoute: typeof FavouritesRoute
  MapRoute: typeof MapRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  ProfileRoute: typeof ProfileRoute
  ProfileeditRoute: typeof ProfileeditRoute
  AdminCspIdRoute: typeof AdminCspIdRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDashboard2Route: typeof AdminDashboard2Route
  AdminOrganisationsRoute: typeof AdminOrganisationsRoute
  AuthAdminOnlyRoute: typeof AuthAdminOnlyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRequestRoute: typeof AuthRequestRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CspProjectIDRoute: typeof CspProjectIDRoute
  OrganisationsProjectIdRoute: typeof OrganisationsProjectIdRoute
  OrganisationsDashboardRoute: typeof OrganisationsDashboardRoute
  OrganisationsEditprofileRoute: typeof OrganisationsEditprofileRoute
  OrganisationsNewRoute: typeof OrganisationsNewRoute
  OrganisationsProfileRoute: typeof OrganisationsProfileRoute
  CspCspIdApplyRoute: typeof CspCspIdApplyRoute
  OrganisationsListingNewRoute: typeof OrganisationsListingNewRoute
  OrganisationsPreviewProjectPreviewRoute: typeof OrganisationsPreviewProjectPreviewRoute
  OrganisationsApplicantProjectIdApplicantIdRoute: typeof OrganisationsApplicantProjectIdApplicantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profileedit': {
      id: '/profileedit'
      path: '/profileedit'
      fullPath: '/profileedit'
      preLoaderRoute: typeof ProfileeditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-table-demo': {
      id: '/data-table-demo'
      path: '/data-table-demo'
      fullPath: '/data-table-demo'
      preLoaderRoute: typeof DataTableDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/profile': {
      id: '/organisations/profile'
      path: '/organisations/profile'
      fullPath: '/organisations/profile'
      preLoaderRoute: typeof OrganisationsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/new': {
      id: '/organisations/new'
      path: '/organisations/new'
      fullPath: '/organisations/new'
      preLoaderRoute: typeof OrganisationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/editprofile': {
      id: '/organisations/editprofile'
      path: '/organisations/editprofile'
      fullPath: '/organisations/editprofile'
      preLoaderRoute: typeof OrganisationsEditprofileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/dashboard': {
      id: '/organisations/dashboard'
      path: '/organisations/dashboard'
      fullPath: '/organisations/dashboard'
      preLoaderRoute: typeof OrganisationsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/$projectId': {
      id: '/organisations/$projectId'
      path: '/organisations/$projectId'
      fullPath: '/organisations/$projectId'
      preLoaderRoute: typeof OrganisationsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/$projectID': {
      id: '/csp/$projectID'
      path: '/csp/$projectID'
      fullPath: '/csp/$projectID'
      preLoaderRoute: typeof CspProjectIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/request': {
      id: '/auth/request'
      path: '/auth/request'
      fullPath: '/auth/request'
      preLoaderRoute: typeof AuthRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/adminOnly': {
      id: '/auth/adminOnly'
      path: '/auth/adminOnly'
      fullPath: '/auth/adminOnly'
      preLoaderRoute: typeof AuthAdminOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organisations': {
      id: '/admin/organisations'
      path: '/admin/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AdminOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard2': {
      id: '/admin/dashboard2'
      path: '/admin/dashboard2'
      fullPath: '/admin/dashboard2'
      preLoaderRoute: typeof AdminDashboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cspId': {
      id: '/admin/cspId'
      path: '/admin/cspId'
      fullPath: '/admin/cspId'
      preLoaderRoute: typeof AdminCspIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/preview/$projectPreview': {
      id: '/organisations/preview/$projectPreview'
      path: '/organisations/preview/$projectPreview'
      fullPath: '/organisations/preview/$projectPreview'
      preLoaderRoute: typeof OrganisationsPreviewProjectPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/listing/new': {
      id: '/organisations/listing/new'
      path: '/organisations/listing/new'
      fullPath: '/organisations/listing/new'
      preLoaderRoute: typeof OrganisationsListingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/$cspId/apply': {
      id: '/csp/$cspId/apply'
      path: '/csp/$cspId/apply'
      fullPath: '/csp/$cspId/apply'
      preLoaderRoute: typeof CspCspIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/applicant/$projectId/$applicantId': {
      id: '/organisations/applicant/$projectId/$applicantId'
      path: '/organisations/applicant/$projectId/$applicantId'
      fullPath: '/organisations/applicant/$projectId/$applicantId'
      preLoaderRoute: typeof OrganisationsApplicantProjectIdApplicantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DataTableDemoRoute: DataTableDemoRoute,
  DiscoverRoute: DiscoverRoute,
  FavouritesRoute: FavouritesRoute,
  MapRoute: MapRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  ProfileRoute: ProfileRoute,
  ProfileeditRoute: ProfileeditRoute,
  AdminCspIdRoute: AdminCspIdRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDashboard2Route: AdminDashboard2Route,
  AdminOrganisationsRoute: AdminOrganisationsRoute,
  AuthAdminOnlyRoute: AuthAdminOnlyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRequestRoute: AuthRequestRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CspProjectIDRoute: CspProjectIDRoute,
  OrganisationsProjectIdRoute: OrganisationsProjectIdRoute,
  OrganisationsDashboardRoute: OrganisationsDashboardRoute,
  OrganisationsEditprofileRoute: OrganisationsEditprofileRoute,
  OrganisationsNewRoute: OrganisationsNewRoute,
  OrganisationsProfileRoute: OrganisationsProfileRoute,
  CspCspIdApplyRoute: CspCspIdApplyRoute,
  OrganisationsListingNewRoute: OrganisationsListingNewRoute,
  OrganisationsPreviewProjectPreviewRoute:
    OrganisationsPreviewProjectPreviewRoute,
  OrganisationsApplicantProjectIdApplicantIdRoute:
    OrganisationsApplicantProjectIdApplicantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
